# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/saschakohler/.oh-my-zsh"

# diasble npm warnings
export NODE_NO_WARNINGS=1
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=""

plugins=(git zsh-autosuggestions zsh-syntax-highlighting web-search)

source $ZSH/oh-my-zsh.sh
export XDG_CONFIG_HOME="$HOME/.config"
# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

#export LC_ALL=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

export FZF_TMUX_OPTS="-p"
#needed for Android Development
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH="$PATH:/usr/local/texlive/2024basic/bin/universal-darwin"
#---------- Prompt ------------

PURE_GIT_PULL=0
autoload -U promptinit; promptinit
prompt pure




########################################################
##### ALIASES
########################################################
alias ll='eza -lbF --git'
alias la='eza -lbhHigmuSa --time-style=long-iso --git --color-scale'
alias lx='eza -lbhHigmuSa@ --time-style=long-iso --git --color-scale'
alias llt='eza -l --git --tree'
## Sorts
alias llm='eza -lbGF --git --sort=modified'
alias lld='eza -lbhHFGmuSa --group-directories-first'
# alias ll="eza -l -g --icons"
# alias lla="eza -l -g --icons -a"
alias llg="eza -l -g --git"
# alias llt="eza --tree -g --level=2 --icons"
# Compilation flags
# export ARCHFLAGS="-arch x86_64"
alias g='git'
alias e='exit'
alias lg='lazygit'
alias v='nvim'
alias t='tmux'
alias c='clear'
alias tm='tmuxinator'


## Kubernetes aliases
alias k=kubectl
# alias kconf='__create_separate_kubeconfig.sh'
alias kdump='kubectl get all --all-namespaces'
alias kaf='kubectl apply -f'
alias kdf='kubectl delete -f'
# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias zt='cd /Users/saschakohler/garden/zet/'
alias zshconfig="v ~/.zshrc"
alias k='kubectl'
alias tui='taskwarrior-tui'

export EDITOR='nvim'

#
export KUBE_EDITOR="nvim"
export SECOND_BRAIN="$HOME/Documents/01_Development/Active_Projects/garden"

export PATH="$(brew --prefix python)/libexec/bin:$PATH"
# ezample aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
export PATH="/usr/local/opt/php@8.1/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export FZF_DEFAULT_COMMAND="fd --type f"
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="/usr/local/opt/node@18/bin:$PATH"
eval "$(zoxide init zsh)"

function f_enter() {
  BUFFER="~/dev/dotfiles/scripts/__open_file.sh"
  zle accept-line
}

zle -N f_enter
bindkey '^f' f_enter     

source ~/dev/dotfiles/scripts/__grep_and_open.sh
bindkey -s '^[q' 'gif\n'                  # Alt+q: Inserts 'gif' and a newline

# --------------------history-------------------- 
#
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

. "$HOME/.local/bin/env"

# Added by Windsurf
export PATH="/Users/saschakohler/.codeium/windsurf/bin:$PATH"

# opencode
export PATH=/Users/saschakohler/.opencode/bin:$PATH
export PATH="/opt/homebrew/opt/mysql/bin:$PATH"
